### ISSUE TITLE
Reducing precision and size of html

### ISSUE THREAD

**Issue by statquant** [dreamRs/uPlot-r#1]
Hello, thank you very much for your package. Looking at the html produced it looks that numbers are stored as text with high precision. Is there a way to decrease the number of digits for precision?
Going further is there any way to store data in some binary form to reduce size?
Many thanks

**Comment by pvictor** [comment]
Hello,
Thanks for your interest in this package!

For the problem of number precision, I think it's best to modify the data itself before constructing the graph.
To reduce size of the generated config we can try to use gzipped JSON instead of plain json, through {jsonlite} it's quite straightforward : 

```r
gzjson <- jsonlite::as_gzjson_b64(ggplot2::diamonds)
print(object.size(gzjson), units = "Mb")
# 0.9 Mb

json <- jsonlite::toJSON(ggplot2::diamonds)
print(object.size(json), units = "Mb")
# 6.2 Mb
```
After we just need to adapt javascript bindings to parse the gzipped json. This would reduce the output size, but would add processing time to generate the graphic and display it in the browser.

**Comment by statquant** [comment]
Hello, thanks for your answer.
Are you suggesting I transform my data before passing it to the plot function?
Would that work? I would expect the type to remain unchanged hence the number of digits to remain the same.
Would you kindly point me to where this is handled? I confess I could not find in looking at R/
The speed of rendering is my first priority and I think this would help

**Comment by pvictor** [comment]
Yes you can transform your data before, by default all decimals are used (up to 15 I think) by the JSON parser, you can also declare an option to specify the number of decimals to use, here's an example:

```r
notrounded <- uPlot(data.frame(
  date = Sys.Date() - seq_len(1e4),
  values = rnorm(1e4)
))
htmlwidgets::saveWidget(notrounded, file = "notrounded.html", selfcontained = TRUE)
fs::file_size("notrounded.html")
# 429K

rounded <- uPlot(data.frame(
  date = Sys.Date() - seq_len(1e4),
  values = round(rnorm(1e4), 4)
))
htmlwidgets::saveWidget(rounded, file = "rounded.html", selfcontained = TRUE)
fs::file_size("rounded.html")
# 319K

options(htmlwidgets.TOJSON_ARGS = list(digits = 2)) # only two digits
notrounded_w_option <- uPlot(data.frame(
  date = Sys.Date() - seq_len(1e4),
  values = rnorm(1e4)
))
htmlwidgets::saveWidget(notrounded_w_option, file = "notrounded_w_option.html", selfcontained = TRUE)
fs::file_size("notrounded_w_option.html")
# 263K
```

I also added an option to gzip JSON data, here's an example of the difference in output size:

```r
normal <- uPlot(
  data = eco2mix[, c(1, 3:9)],
  use_gzipped_json = FALSE
)
htmlwidgets::saveWidget(normal, file = "normal.html", selfcontained = TRUE)
fs::file_size("normal.html")
# 7.92M


gzipped <- uPlot(
  data = eco2mix[, c(1, 3:9)],
  use_gzipped_json = TRUE
)
htmlwidgets::saveWidget(gzipped, file = "gzipped.html", selfcontained = TRUE)
fs::file_size("gzipped.html")
# 3.46M
```

**Comment by statquant** [comment]
That looks amazing!!! Thanks so much
I expect the rendering is going to be much faster as well with digits = 4.
For further speed up I'll try to swap jsonlite for yyjsonr or rcppsimdjson

**Comment by statquant** [comment]
Thank you very much it’s working perfectly
